# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loocv <- function(O, y, b, lambda) {
    .Call('_RWNN_loocv', PACKAGE = 'RWNN', O, y, b, lambda)
}

importance_score <- function(X, W) {
    .Call('_RWNN_importance_score', PACKAGE = 'RWNN', X, W)
}

classify_cpp <- function(y, C, t, b) {
    .Call('_RWNN_classify_cpp', PACKAGE = 'RWNN', y, C, t, b)
}

estimate_output_weights <- function(O, y, lnorm, lambda) {
    .Call('_RWNN_estimate_output_weights', PACKAGE = 'RWNN', O, y, lnorm, lambda)
}

rwnn_forward <- function(X, W, activation, bias) {
    .Call('_RWNN_rwnn_forward', PACKAGE = 'RWNN', X, W, activation, bias)
}

